version: '3'
services:
  crawler:
    build: .
    command: python main.py
    env_file:
      - .env
    volumes:
      - ".:/otodom-crawler"
    links:
      - redis
  redis:
    image: redis:latest
